version: '3.8'

services:
  db:
    image: postgres:16-alpine3.18
    container_name: pgress
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    image: simpletodo:latest
    container_name: app
    ports:
      - "5000:5000"
